### ISSUE TITLE
Enable installation of plugins

### ISSUE THREAD

**Issue by mewm** [geerlingguy/ansible-role-logstash#12]
@geerlingguy I was thinking about making a pull request with the options to enable/install (some) logstash plugins. 
Is this something you'd like in this repo, or would you prefer I create a separate role, tagging this as a dependency?

**Comment by geerlingguy** [comment]
@mewm - I think a separate role might be more appropriate (just to keep this role's complexity more limited, and since many people don't use plugins with logstash).

**Comment by geerlingguy** [comment]
Thinking further on this, it's probably something that would be helpful to have built-in.

**Comment by geerlingguy** [comment]
I was working on this locally, I'll have it up in the repo soon, along with some other changes for 'modern' logstash.
