### ISSUE TITLE
Get [No such file or directory: '/opt/logstash'] error on Ubuntu 16.04

### ISSUE THREAD

**Issue by eli-betito** [geerlingguy/ansible-role-logstash#23]
Hi,

I tried to install logstash using your Ansible GitHub's code but unfortunately I got this error:
**"No such file or directory: '/opt/logstash'"** **"MODULE FAILURE"**

The /opt/logstash folder is empty and not used in this Ubuntu 16.04 version however the folder that is being used is /etc/logstash.

ls /etc/logstash
conf.d (Directory)
log4j2.properties
startup.options
jvm.options
logstash.yml

Can you assist please ?

**Comment by runtman** [comment]
It looks like it gets install in /usr/share/logstash for Ubuntu16.
