### ISSUE TITLE
Fail on TASK: Get list of installed plugins.

### ISSUE THREAD

**Issue by uschtwill** [geerlingguy/ansible-role-logstash#25]
Apparently, because the dir /opt/logstash doesn't exist (yet)?!

**Comment by uschtwill** [comment]
No, actually it seems it should be 

```
---
- name: Get list of installed plugins.
  command: >
    ./bin/logstash-plugin list
    chdir=/usr/share/logstash
  register: logstash_plugins_list
  changed_when: false

- name: Install configured plugins.
  command: >
    ./bin/logstash-plugin install {{ item }}
    chdir=/usr/share/logstash
  with_items: "{{ logstash_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
  notify: restart logstash
```

instead of 

```
---
- name: Get list of installed plugins.
  command: >
    ./bin/logstash-plugin list
    chdir=/opt/logstash
  register: logstash_plugins_list
  changed_when: false

- name: Install configured plugins.
  command: >
    ./bin/logstash-plugin install {{ item }}
    chdir=/opt/logstash
  with_items: "{{ logstash_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
  notify: restart logstash
```

Probably a 5.x change?

**Comment by Lusitaniae** [comment]
I confirm, more details here: 
https://www.elastic.co/guide/en/logstash/current/breaking-changes.html#_release_packages

**Comment by maharg101** [comment]
https://github.com/geerlingguy/ansible-role-logstash/pull/32 works for me 👍

**Comment by geerlingguy** [comment]
I believe this has been fixed by a bit of a rewrite of the role (role version 4.0.0) to work with modern versions of logstash; see https://github.com/geerlingguy/ansible-role-logstash/commit/a1c342cc57c83d7ee8d1d87f340a11a7884b2405

Please re-open if you believe this issue is still relevant. Thanks!
