### ISSUE TITLE
Disable default config installation

### ISSUE THREAD

**Issue by mgodlewski** [geerlingguy/ansible-role-logstash#31]
The role installs this configuration at least :
```
    - 01-beats-input.conf
    - 10-syslog.conf
    - 11-nginx.conf
    - 12-apache.conf
    - 14-solr.conf
    - 15-drupal.conf
    - 30-elasticsearch-output.conf
```
It should be configurable to not install this configuration.
The logstash configuration should be handled by another dedicated role, project dependant.

**Comment by mgodlewski** [comment]
Done in https://github.com/mgodlewski/ansible-role-logstash/pull/8

**Comment by astik** [comment]
Any chance to do a pull request for this feature ?
It seems more flexible and more customizable, it would be great to have this in the original project and not in a fork =D

**Comment by mgodlewski** [comment]
The pull request #34 implements this. But hasn't been merged since september 2017. My gues is that geerlingguy has no time to maintain this role.

**Comment by astik** [comment]
@mgodlewski i found your approach cleaner as there is only one property for all conf (general conf, input, output and filters), no need to split things as they all end up in the same conf directory (/etc/logstash/conf.d)

**Comment by nickmaccarthy** [comment]
+1 on this.  There is a great role to get logstash and up and running real quick, but config management should come a separate, user maintained role anyways.  The ability to implement a variable that would turn on and off the default configs like @mgodlewski made would be great.  @geerlingguy any chance you can merge #34?

**Comment by meersjo** [comment]
Another upvote for this. Don't need all the default entries, and I don't even necesarily want default target elastics - a single instance could very well serve multiple sources to multiple clusters.

**Comment by meersjo** [comment]
Ping to keep open; issue already has PR ready.

**Comment by meersjo** [comment]
Ping to keep open; issue already has PR ready.

**Comment by ruester** [comment]
I would also like to have the opportunity to disable the installation of the filter configurations. Otherwise the elasticsearch output in some cases does not know about `%{[@metadata][beat]}` and will not replace it, so there will be an index with the name `%{[@metadata][beat]}-2020.06.24` created.

**Comment by nicenemo** [comment]
@geerlingguy  This role ise useful but the hard coded config is annoying. If you have some time, at least have a disabled flag and perhaps disabled by default. There is a merge request available.

**Comment by vadimkuragkovskiy** [comment]
Ping to keep open

**Comment by djburns** [comment]
Raised PR #69  to resolve this by adding a variable to control if the defaults get added or not. It defaults to adding them in order to maintain backwards compatibility.
