### ISSUE TITLE
Multiline filter issue with solr

### ISSUE THREAD

**Issue by Trans-IP** [geerlingguy/ansible-role-logstash#41]
Thereis a multiline filter reference in this filter that fails in Logstash 6.12 because there is no multiline filter installed anymore, just the codec:  

ansible-role-logstash/files/filters/14-solr.conf
```
  multiline {
      pattern => "(([^\s]+)Exception.+)|(at:.+)"
      stream_identity => "%{logsource}.%{@type}"
      what => "previous"
    }
```

The symptom was Logstash would start and would not bind on port 5044.  The log showed an error

> ERROR] 2018-09-29 01:26:13.695 [LogStash::Runner] agent - Cannot create pipeline {:reason=>"Couldn't find any filter plugin named 'multiline'. Are you sure this is correct? Trying to load the multiline filter plugin resulted in this error: Problems loading the requested plugin named multiline of type filter. Error: NameError NameError"}

Removing this conf allowed Logstash to listen on port 5044 successfully.  It was a bit confusing because the process was started, just not listening on the beats input port.

**Comment by rastaman** [comment]
Hi,

You can also change `multiline` to `codec => multiline` instead of disabling the filter.

**Comment by metamaker** [comment]
Same for me.

**Comment by bengawel** [comment]
Same as well.

**Comment by bobdoah** [comment]
I've submitted Pull Request #47 which removes this.

**Comment by lunarthegrey** [comment]
Same for me as well, if you don't want to remove the conf you can just run this:

`/usr/share/logstash/bin/logstash-plugin install logstash-filter-multiline`

**Comment by rthornton128** [comment]
A more Ansible solution would be to override the variable `logstash_install_plugins`. Something like:
``` yaml
    - name: Setup Logstash
      role: geerlingguy.logstash
      vars:
        logstash_install_plugins:
        - logstash-input-beats
        - logstash-filter-multiline
```
