### ISSUE TITLE
UseParNewGC error on Ubuntu 18.04

### ISSUE THREAD

**Issue by shahinism** [geerlingguy/ansible-role-logstash#46]
The [ansible-java-role](https://github.com/geerlingguy/ansible-role-java) installs Java 10 on Ubuntu 18.04 recently and since `UseParNewGC` is deprecated in Java 9 and completely removed from Java 10 ([source](https://bugs.openjdk.java.net/browse/JDK-8151084)), this role (`ansible-role-logstash`) will fail in installation step. It's good to mention this issue somewhere in the readme file, so users are aware that they need to define a working Java version in their playbook like this:

``` yml
  vars:
    - java_packages:
      - openjdk-8-jre
```

Thanks for your great works :-)

**Comment by geerlingguy** [comment]
Thanks, I've added a bit to the example playbook (which is modeled after the molecule test playbook), and hopefully that will help people get through this a little more easily.
